In [1]:
import torch
from torch.autograd import Variable
import torch.nn as nn
import torch.nn.functional as F

In [2]:
class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.fc1 = nn.Linear(1,1)
    def forward(self, x):
        x = self.fc1(x) # y=Ax+b
        return x

In [3]:
net = Net()
print(net)

Net(
  (fc1): Linear(in_features=1, out_features=1, bias=True)
)


In [4]:
print(list(net.parameters()))

[Parameter containing:
tensor([[0.3541]], requires_grad=True), Parameter containing:
tensor([0.8654], requires_grad=True)]


In [5]:
input = Variable(torch.randn(1,1,1), requires_grad=True) #1x1x1 -> one value
print(input)

tensor([[[0.0654]]], requires_grad=True)


In [6]:
out = net(input)
print(out)

tensor([[[0.8885]]], grad_fn=<AddBackward0>)


In [7]:
import torch.optim as optim
def criterion(out, label):
    return (label - out)**2
optimizer = optim.SGD(net.parameters(), lr=0.01, momentum=0.5)

In [8]:
data = [(1,3), (2,6), (3,9), (4,12), (5,15), (6,18)] # Ax + b will be that A=3 and b=0

In [9]:
for epoch in range(100):
    for i, data2 in enumerate(data):
        X, Y = iter(data2)
        X, Y = Variable(torch.FloatTensor([X]), requires_grad=True), Variable(torch.FloatTensor([Y]), requires_grad=False)
        optimizer.zero_grad()
        outputs = net(X)
        loss = criterion(outputs, Y)
        loss.backward()
        optimizer.step()
        if (i % 10 == 0):
            print("Epoch {} - loss: {}".format(epoch, loss.data[0]))

Epoch 0 - loss: 3.1702725887298584
Epoch 1 - loss: 3.3892197608947754
Epoch 2 - loss: 1.1305524110794067
Epoch 3 - loss: 1.5047433376312256
Epoch 4 - loss: 1.1845000982284546
Epoch 5 - loss: 1.1217557191848755
Epoch 6 - loss: 0.9912065267562866
Epoch 7 - loss: 0.8985068202018738
Epoch 8 - loss: 0.8067928552627563
Epoch 9 - loss: 0.7269871234893799
Epoch 10 - loss: 0.6542245149612427
Epoch 11 - loss: 0.5890275835990906
Epoch 12 - loss: 0.5302342176437378
Epoch 13 - loss: 0.4773399531841278
Epoch 14 - loss: 0.4297117292881012
Epoch 15 - loss: 0.38683977723121643
Epoch 16 - loss: 0.34824368357658386
Epoch 17 - loss: 0.3134992718696594
Epoch 18 - loss: 0.2822204828262329
Epoch 19 - loss: 0.25406304001808167
Epoch 20 - loss: 0.22871442139148712
Epoch 21 - loss: 0.20589567720890045
Epoch 22 - loss: 0.1853528618812561
Epoch 23 - loss: 0.16685955226421356
Epoch 24 - loss: 0.15021172165870667
Epoch 25 - loss: 0.13522492349147797
Epoch 26 - loss: 0.12173326313495636
Epoch 27 - loss: 0.1095878928

In [10]:
print(list(net.parameters()))

[Parameter containing:
tensor([[2.9985]], requires_grad=True), Parameter containing:
tensor([0.0087], requires_grad=True)]


In [11]:
print(net(Variable(torch.Tensor([[[1]]]))))

tensor([[[3.0071]]], grad_fn=<AddBackward0>)


In [12]:
class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.fc1 = nn.Linear(1,10)
        self.fc2 = nn.Linear(10,1)
    def forward(self, x):
        x = self.fc2(self.fc1(x))
        return x